### PR TITLE
restangular storage updateObjectFromResult fixes

### PR DESCRIPTION
**Pull request by christophehurpeau**

### CODE REVIEW

**Comment by cyrilf** [comment]
Ok. Seems good to me. Great. (I'll try to don't forget that my code need to be updated ;) )

And I'm really waiting for ES6 (default params here)

**Comment by christophehurpeau** [comment]
If everyone is ok with it, we can start using babeljs

**Comment by christophehurpeau** [comment]
But last time I asked there wasn't much enthusiasm about it

**Comment by cyrilf** [comment]
Let's merge this and we'll launch the Babel debate later on. You merge and tag it (so I can use it right now), or I can do it if you prefer?

**Pull request merged**
